version: '3.7'

name: easy-log

services:
  easy-log:
    image: ${EASY_LOG}
    container_name: easy-log
    environment:
      - HEAP_SIZE=512m
      - ES_ADDRESS=172.16.8.31:9200,172.16.8.31:9201,172.16.8.31:9202
      - ES_HOT_MAX_AGE=10m
      - ES_HOT_MAX_PRIMARY_SHARD_SIZE=1gb
      - ES_HOT_MAX_DOCS=10000000
      - ES_DELETE_MIN_AGE=1d
      - MQTT_HOST=121.36.96.79
      - MQTT_PORT=1883
      - REDIS_HOST=114.217.55.239
      - REDIS_PORT=6379
      - REDIS_DATABASE=3
      - REDIS_PASSWORD=ICONMAN20220106R
      - EL_ADMIN_ENABLE=true
      - EL_ADMIN_USERNAME=admin
      - EL_ADMIN_PASSWORD=123456
      - EL_ADMIN_MQTT_ADDRESS=ws://121.36.96.79:8083/mqtt
      - EL_COMPUTE_ENABLE=true
      - EL_COLLECTOR_ENABLE=true
      - EL_COLLECTOR_QUEUE_CAPACITY=100000
      - EL_COLLECTOR_INSERT_BATCH_SIZE=500

    volumes:
      - easy-log:/app
    ports:
      - "2124:1124"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:1124/monitor/health" ]
      start_period: 3s
      retries: 3

volumes:
  easy-log:
    driver: local

networks:
  default:
    external: true
    name: el_net