logging:
  config: classpath:logback-spring.xml
  level:
    root: info
#    tracer: trace
    fun.tan90.easy.log: debug
    fun.tan90.easy.log.admin: debug
    fun.tan90.easy.log.compute: debug
    fun.tan90.easy.log.collector: debug

tlog:
  mdc-enable: true