spring:
  redis:
    host: ${REDIS_HOST:172.16.8.31}
    port: ${REDIS_PORT:6379}
    database: ${REDIS_DATABASE:5}
    password: ${REDIS_PASSWORD:root@123456!}
    connect-timeout: 5000ms
    lettuce:
      pool:
        enabled: true
        max-idle: 50
        min-idle: 10
        max-active: 300
        max-wait: -1ms

sa-token:
  alone-redis:
    timeout: 5000ms
    database: ${spring.redis.database}
    host: ${spring.redis.host}
    port: ${spring.redis.port}
    password: ${spring.redis.password}