spring:
  redis:
    host: ${REDIS_HOST:114.217.55.239}
    port: ${REDIS_PORT:6379}
    database: ${REDIS_DATABASE:3}
    password: ${REDIS_PASSWORD:ICONMAN20220106R}
    connect-timeout: 5000ms
    lettuce:
      pool:
        enabled: true
        max-idle: 50
        min-idle: 10
        max-active: 300
        max-wait: -1ms