spring:
  redis:
    cluster:
      nodes: 172.16.8.31:7000,172.16.8.31:7001,172.16.8.31:7002,172.16.8.31:7003,172.16.8.31:7004,172.16.8.31:7005
      max-redirects: 2
    password: ${REDIS_PASSWORD:root@123456!}
    connect-timeout: 5000ms
    lettuce:
      pool:
        enabled: true
        max-idle: 50
        min-idle: 10
        max-active: 300
        max-wait: -1ms

sa-token:
  alone-redis:
    timeout: 5000ms
    cluster:
      nodes: ${spring.redis.cluster.nodes}
      max-redirects: ${spring.redis.cluster.max-redirects}
    password: ${spring.redis.password}
