mqtt:
  client:
    enabled: true
    ip: ${MQTT_HOST:172.16.8.31}
    port: ${MQTT_PORT:1883}
    # 固定前缀不能修改
    clientId: easy_log_server:${random.long(1000,9999)}
    keep-alive-secs: 30
    user-name: admin
    password: 123456