easy-log:
  es:
    address: 172.16.8.31:9200,172.16.8.31:9201,172.16.8.31:9202
    index-lifecycle-policy:
      hot-max-age: 10m
      hot-max-primary-shard-size: 1gb
      hot-max-docs: 10000000
      delete-min-age: 1d
  admin:
    enable: true
    banner: true
    auth: true
    validate-captcha: true
    username: admin
    password: 123456
    mqtt-broker-url: ws://121.36.96.79:9183/mqtt
  compute:
    enable: true
    banner: true
    consumer-global-orders: 1,2,3,4
  collector:
    enable: true
    banner: true
    queue-capacity: 10240
    insert-batch-size: 200
    consumer-global-orders: 1,2,3,4
