easy-log:
  es:
    address: 172.16.8.31:9200,172.16.8.31:9201,172.16.8.31:9202
  stream:
    poll-timeout: 1s
    pull-batch-size: 100
  admin:
    enable: true
    banner: true
    auth: false
    init-index-cron: 0 0 23 * * ?
    stats-log-speed-cron: 0/2 * * * * ?
    username: admin
    password: 123456
    validate-captcha: false
  compute:
    enable: ${easy-log.admin.enable}
    banner: true
    consumer-global-orders: 1,2,3,4
  collector:
    enable: true
    banner: true
    insert-batch-size: 200
    consumer-global-orders: 1,2,3,4
    queue-capacity: 10240
