server:
  port: 1203

spring:
  application:
    name: easy-log-server
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: dev
    group:
      dev:
        - cache
        - el
        - log