server:
  port: 1124

spring:
  application:
    name: easy-log-server
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  reactor:
    debug-agent:
      enabled: false
  thymeleaf:
    cache: false
    mode: HTML
    prefix: classpath:/templates/
  profiles:
    active: dev
    group:
      dev:
        - auth
        - actuator
        - cache
        - el
        - log
        - mqtt
