mqtt:
  server:
    enabled: ${easy-log.admin.enable}
    port: 1883
    name: Easy-Log-Mqtt-Server
    heartbeat-timeout: 20000
    debug: false
    stat-enable: false
    web-port: 8083

  client:
    enabled: ${easy-log.compute.enable}
    ip: 127.0.0.1
    port: 1883
    name: easy-log-compute
    clientId: easy_log_compute:${random.long(1000,9999)}
    keep-alive-secs: 30

mica:
  redis:
    stream:
      enable: true
      poll-timeout: 1s
      poll-batch-size: 100