logging:
  config: classpath:logback-spring.xml
  level:
    root: info
#    tracer: trace
    easy-log: debug
    com.chj.easy.log.admin: debug
    com.chj.easy.log.compute: debug
    com.chj.easy.log.collector: debug

tlog:
  mdc-enable: true