easy-log:
  es:
    address: 172.16.8.31:9200,172.16.8.31:9201,172.16.8.31:9202
    index-lifecycle-policy:
      rollover-max-age: 10m
      delete-min-age: 1d
  stream:
    poll-timeout: 1s
    pull-batch-size: 100
  admin:
    enable: true
    banner: true
    auth: false
    validate-captcha: false
    username: admin
    password: 123456
  compute:
    enable: true
    banner: true
    consumer-global-orders: 1,2,3,4
  collector:
    enable: true
    banner: true
    consumer-global-orders: 1,2,3,4
    insert-batch-size: 200
    queue-capacity: 10240
