easy-log:
  es:
    address: ${ES_ADDRESS:172.16.8.31:9200,172.16.8.31:9201,172.16.8.31:9202}
    index-lifecycle-policy:
      hot-max-age: ${ES_HOT_MAX_AGE:10m}
      hot-max-primary-shard-size: ${ES_HOT_MAX_PRIMARY_SHARD_SIZE:1gb}
      hot-max-docs: ${ES_HOT_MAX_DOCS:10000000}
      delete-min-age: ${ES_DELETE_MIN_AGE:1d}
  admin:
    enable: ${EL_ADMIN_ENABLE:true}
    banner: true
    auth: true
    validate-captcha: true
    mqtt-ws-address: ${EL_ADMIN_MQTT_WS_ADDRESS:ws://${mqtt.client.ip}:8083/mqtt}
    username: ${EL_ADMIN_USERNAME:admin}
    password: ${EL_ADMIN_PASSWORD:123456}
  compute:
    enable: ${EL_COMPUTE_ENABLE:true}
    banner: true
  collector:
    enable: ${EL_COLLECTOR_ENABLE:true}
    banner: true
    queue-capacity: ${EL_COLLECTOR_QUEUE_CAPACITY:100000}
    insert-batch-size: ${EL_COLLECTOR_INSERT_BATCH_SIZE:500}