mqtt:
  server:
    enabled: true
    port: 1883
    name: Easy-Log-Mqtt-Server
    heartbeat-timeout: 20000
    debug: true
    stat-enable: true
    web-port: 8083

mica:
  redis:
    stream:
      enable: true
      poll-timeout: 1s
      poll-batch-size: 100