server:
  port: 1203

spring:
  application:
    name: easy-log-app-event
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: dev
    group:
      dev:
        - actuator
        - cache
        - log
        - mqtt