version: '3.7'
services:
  easy-log-admin01:
    image: ${image}
    container_name: easy-log-admin01
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - HEAP_SIZE=${heap_size}
      - easy-log.admin.enable=true
      - easy-log.compute.enable=false
      - easy-log.collector.enable=false
    volumes:
      - easy-log-admin01:/app
    ports:
      - "2203:1203"
      - "2204:1883"
      - "2205:8083"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:1203/monitor/health" ]
      start_period: 3s
      retries: 3

  easy-log-compute01:
    image: ${image}
    container_name: easy-log-compute01
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - HEAP_SIZE=${heap_size}
      - easy-log.admin.enable=false
      - easy-log.compute.enable=true
      - easy-log.collector.enable=false
      - consumer-global-orders=5,6,7,8
    volumes:
      - easy-log-compute01:/app
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:1203/monitor/health" ]
      start_period: 3s
      retries: 3

  easy-log-collector01:
    image: ${image}
    container_name: easy-log-collector01
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - HEAP_SIZE=${heap_size}
      - easy-log.admin.enable=false
      - easy-log.compute.enable=false
      - easy-log.collector.enable=true
      - consumer-global-orders=5,6,7,8
    volumes:
      - easy-log-collector01:/app
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:1203/monitor/health" ]
      start_period: 3s
      retries: 3

volumes:
  easy-log-admin01:
    driver: local
  easy-log-compute01:
    driver: local
  easy-log-collector01:
    driver: local

networks:
  default:
    external: true
    name: el_net