version: '3.7'

services:
  nginx:
    image: nginx:1.25.2
    restart: always
    container_name: nginx
    ports:
      - "1883:1883"
      - "8083:8083"
      - "18083:18083"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - emqx1
      - emqx2

  emqx1:
    image: emqx:5.1.0
    container_name: emqx1
    environment:
    - "EMQX_NODE_NAME=emqx@node1.emqx.io"
    - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
    - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.io,emqx@node2.emqx.io]"
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx_ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    networks:
      default:
        aliases:
        - node1.emqx.io
    volumes:
      - ./emqx_data_01:/opt/emqx/data
      - ./config/acl.conf:/opt/emqx/etc/acl.conf
      - ./config/emqx.conf:/opt/emqx/etc/emqx.conf

  emqx2:
    image: emqx:5.1.0
    container_name: emqx2
    environment:
    - "EMQX_NODE_NAME=emqx@node2.emqx.io"
    - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
    - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.io,emqx@node2.emqx.io]"
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx_ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    networks:
      default:
        aliases:
        - node2.emqx.io
    volumes:
      - ./emqx_data_02:/opt/emqx/data
      - ./config/acl.conf:/opt/emqx/etc/acl.conf
      - ./config/emqx.conf:/opt/emqx/etc/emqx.conf

networks:
  default:
    external: true
    name: el_net
