mqtt:
  client:
    enabled: true
    ip: ${MQTT_HOST:121.36.96.79}
    port: ${MQTT_PORT:1883}
    name: easy_log_server
    clientId: easy_log_server:${random.long(1000,9999)}
    keep-alive-secs: 30

mica:
  redis:
    stream:
      enable: true
      poll-timeout: 1s
      poll-batch-size: 100