spring:
  redis:
    host: 114.217.55.239
    port: 6379
    database: 3
    password: ICONMAN20220106R
    connect-timeout: 5000ms
    lettuce:
      pool:
        enabled: true
        max-idle: 50
        min-idle: 10
        max-active: 300
        max-wait: -1ms