server:
  port: 1134

spring:
  application:
    name: easy-log-server-collector
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: dev
    group:
      dev:
        - cache-iot
        - el
        - log