server:
  port: 1203

spring:
  redis:
    host: 172.16.8.31
    port: 6379
    database: 10
    password: root@123456!
    connect-timeout: 5000ms
    lettuce:
      pool:
        enabled: true
        max-idle: 50
        min-idle: 10
        max-active: 300
        max-wait: -1ms

logging:
  level:
    root: info
  config: classpath:logback-tlog.xml